hotwax/receiving

src/views/Login.vue
src/views/Shipment.vue

Improved css of login and shipment page (#ew2p3r)

---

README.md

Added link to figma file in readme

#10 Added_link_to_Figma_file_in_Readme

---

changelogs/unreleased/-21v4hav.yml
src/store/modules/user/actions.ts

Improved: code to add await for the getProfile action(#21v4hav)

---

changelogs/unreleased/-220krj9.yml
src/views/Shipment.vue

When refreshing on shipment detail page, the data on the page gets cleared
Closes #

Improved: code to get the shipment detail on page mount(#220krj9)

---

changelogs/unreleased/-208dg0z.yml
src/components/PurchaseOrderItem.vue

Improved code by replacing h6 with ion-note for displaying date in PO list item (#208dg0z)

---

src/components/Image.vue
src/store/modules/product/actions.ts
src/store/modules/shipment/actions.ts
src/store/modules/user/actions.ts

Updated the code to resolve warnings(#220ktrc)

---

src/components/Menu.vue
src/router/index.ts
src/views/ShipmentDetails.vue
src/views/Shipments.vue

Updated: names of components and title of receiving page(#220qzdj)

---

changelogs/unreleased/-226abg0.yml
src/store/modules/order/actions.ts
src/views/PurchaseOrders.vue

Getting all the POs of all locations
Closes #
Passed facilityId in the query to only get PO for specific location

Improved: solr-query to pass the facilityId for getting POs(#226abg0)

---

changelogs/unreleased/-226d142.yml
src/store/modules/order/actions.ts
src/views/PurchaseOrders.vue

Getting all POs
Closes #
Added orderStatusId in solr-query to get specific POs

Added: orderStatusId check in the solr-query(#226d142)

---

src/store/modules/shipment/actions.ts

Updated: payload for receive shipment function

---

src/views/PurchaseOrderDetail.vue

Fixed: the issue on progress bar on PO

---

changelogs/unreleased/-21aqct8.yml
src/views/Login.vue
src/views/Settings.vue
src/views/ShipmentDetails.vue
src/views/Shipments.vue

Removed fullscreen=true from ion-content of all pages(#21aqct8)

---

src/store/modules/shipment/actions.ts

Improved: addShipmentItem action when adding item from the PO page(#226h2ax)

---

src/views/AddProductModal.vue
src/views/AddProductToPOModal.vue
src/views/ReceivingHistoryModal.vue

Added slot and updated icon in ion-button(#238uwuv)

---

public/index.html

Added theme color in index.html file

---

changelogs/unreleased/-24wc2vq.yml
src/locales/en.json
src/theme/variables.css
src/views/PurchaseOrderDetail.vue
src/views/PurchaseOrders.vue
src/views/ShipmentDetails.vue
src/views/Shipments.vue

Improved max-width, margin and tags (#24wc2vq)

---

changelogs/unreleased/-23301r3.yml
src/components/ImageModal.vue
src/views/PurchaseOrderDetail.vue
src/views/ShipmentDetails.vue

Improved code so that clicking on thumbnail of image should open it in a modal (#23301r3)

---

changelogs/unreleased/-226h42t.yml
src/store/modules/order/actions.ts
src/store/modules/shipment/actions.ts

Added: default value for property unitCost when calling receiveShipmentItem api(#226h42t)

---

src/api/index.ts
src/views/Login.vue
src/views/Settings.vue

Improved: code to hide option to set baseURL if value available in '.env' file (#29wgkkh).

---

src/views/PurchaseOrders.vue

Updated the code so that search works on orderId and externalOrderId(#2k5zwr1)

---

src/components/ShipmentListItem.vue
src/services/ShipmentService.ts
src/views/Shipments.vue

Implemented:  performFind API for fetching shipments instead of incoming-shipments API (#2p75u56)

---

src/store/modules/order/actions.ts

Closes #120 
Updated the code to set current shipment to default if no record found or api call fails.

Fixed: Incorrect information being displayed on PO details page(#2te5khn)

---

src/store/modules/shipment/actions.ts
src/views/Shipments.vue

Implemented search functionality on shipments page(#2v1npkr)

---

src/store/modules/order/actions.ts

Fixed: type error on po details page

---

src/store/modules/order/actions.ts
src/store/modules/user/actions.ts
src/views/Returns.vue

Updated query for searching PO and fixed default facility location not set on item in case PO history does not exists

---

package-lock.json
package.json

Updated: the app version for the new release

---

src/store/modules/order/actions.ts
src/store/modules/shipment/actions.ts

Closes https://github.com/hotwax/receiving/issues/143

Changed console.log to console.error #hactoberfest

---

package-lock.json
package.json

Upgraded Ionic to 6.2(#2w9wz26)

---

package-lock.json
package.json

preparing release 2.2.0(#32cb8fd)

---

package-lock.json
package.json

Updated: version of package for minor release to 2.3.0

---

package-lock.json
package.json
release-notes.md

Updated: version of package for minor release to 2.4.0

---

package-lock.json
package.json
release-notes.md

Updated version of package for minor release to 2.5.0

---

package-lock.json
package.json
src/main.ts
src/theme/variables.css

Added hotwax-theme-apps package(#85zrj08rb)

---

package-lock.json
package.json
src/App.vue
src/main.ts
src/store/modules/user/actions.ts
src/utils/index.ts

Implemented: Migrated from moment timezone to luxon(#2dewerv)

---

src/store/modules/order/actions.ts
src/store/modules/user/actions.ts

fix: purchase order data not cleared on logout(#85zrkramx)

---

src/views/PurchaseOrderDetail.vue
src/views/ReturnDetails.vue
src/views/ShipmentDetails.vue

Updated: autofocus on ion-input on all details page (#2vd9jaf)

---

.eslintrc.js
src/store/modules/order/actions.ts
src/store/modules/return/actions.ts
src/store/modules/shipment/actions.ts
src/store/modules/user/actions.ts

Fixed: build console warnings (#85zrmq7yv)

---

src/store/modules/order/actions.ts

Improved: show the most recent record in the history modal(#85zrna7wr)

---

src/views/PurchaseOrderDetail.vue

updated: UI for over receiving(#85zrnfx68)

---

src/components/PurchaseOrderItem.vue
src/store/modules/order/actions.ts
src/views/PurchaseOrderDetail.vue

feat: display order and item status on POs(#85zrndfmd)

---

package-lock.json
package.json

Updated: app version for minor release (2.9.0)

---

src/components/ShipmentListItem.vue
src/views/ShipmentDetails.vue
src/views/Shipments.vue

Closes #207 
Before:
Details Page:
After:
Details Page:

Improved: code to display the externalId for shipments on list and detail page if present, otherwise display shipmentId(#85zrvy2rk)

---

src/views/Shipments.vue

Closes #208 
Changed hook from mounted to ionViewWillEnter to always fetch the shipment when coming to the list page

Fixed: issue of shipment not being removed from the list page after receiving(#85zrvy23b)

---

package-lock.json
package.json
release-notes.md

Updated: app version and release notes for minor release(v2.10.0)

---

src/components/PurchaseOrderItem.vue

Order name is primary info

---

src/views/ReturnDetails.vue
src/views/ShipmentDetails.vue

Implemented: over receiving on shipment details and return details page (#85zrx4zww)

---

src/components/Menu.vue

Fixed: show the selected route with secondary color in the menu (#85zrx4jgc)

---

src/views/AddProductModal.vue
src/views/AddProductToPOModal.vue
src/views/PurchaseOrders.vue

Improved: optimised search query by removing wildcards

---

package-lock.json
package.json

Updated: app version for minor release (2.12.0)

---

src/views/AddProductModal.vue
src/views/AddProductToPOModal.vue

Closes #227 
Settings page - 
Add product to PO modal -

Improved: showed product identifications in the add product to PO modal search list (#85zt92ey4)

---

src/views/PurchaseOrders.vue
src/views/Returns.vue
src/views/Shipments.vue

Implemented: pull to refresh on all find screens (#229)

---

package-lock.json
package.json

Updated: app version for minor release (2.13.0)

---

src/views/ReturnDetails.vue

Fixed: receiving button is disabled on the return details page (#243)

---

package-lock.json
package.json

Updated: app version for minor release (2.15.0)

---

package-lock.json
package.json

Updated: package and lock file for minor release(v2.16.0)

---

package-lock.json
package.json

Updated: package.json and package.lock.json for minor release 2.17.0

---

package-lock.json
package.json

Closes #
Updated: package.json and package-lock.json for minor release (2.18.0)

Updated: package.json and package-lock.json for minor release (2.18.0)

---

src/views/Shipments.vue

Closes #
#263 
Fixed: Incoming shipment search (#263).

Fixed: Incoming shipment search (#263).

---

package-lock.json
package.json
src/main.ts
src/views/Settings.vue
vue.config.js

Related Issue: https://github.com/hotwax/dxp-components/issues/177
Used the centralized oms instance navigator on the settings page which is implemented in dxp-components.
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

Implemented: centralized oms instance navigator in settings page from dxp-components (dxp/177)

---

src/App.vue
src/locales/en.json
src/store/modules/user/actions.ts
src/views/Settings.vue

Implemented: support for single logout

---

package-lock.json
package.json

Improved: app version in package and lock file for minor release(v2.19.0)

---

package-lock.json
package.json

Updated: app version for the hot release (2.19.1).

---

.env.example

Improved: product identifier options to have erpId support

---

src/views/PurchaseOrderDetail.vue

Implemented: Added Pointer on Hover for Completed items icon(#271)

---

package-lock.json
package.json

Improved: app version in package and lock file for minor release(v2.21.0)

---

.env.example

Improved: product identifier options to have upca support

---

package-lock.json
package.json

Improved: app version for package and lock file for patch release(v2.21.1)

---

package-lock.json
package.json

Closes #
Updated: app version for the minor release (2.22.0).

Updated: app version for the minor release (2.22.0).

---

package-lock.json
package.json

Updated: app version for minor release (2.23.0)

---

src/views/ShipmentDetails.vue

Improved: replaced scan icon with camera outline icon in shipment details page(#312)

---

src/views/ShipmentDetails.vue

Fixed: case to disable the button when the shipment status is received and improved the UI in case of received shipment(#318)

---

src/views/ShipmentDetails.vue

Fixed: issue of receiving option not displayed on shipment details page

---

src/locales/en.json
src/views/Returns.vue

Closes #331
Changed the placeholder of the searchbar present in returns page.

Improved: searchbar placeholder in returns page (#331)

---

src/views/PurchaseOrderDetail.vue

Closes #271
Improved code for better visibility of completed PO items icon on the PO details page.
Before
After

Improved: code for enhancement of completed items icon (#271)

---

package-lock.json
package.json

Updated: app version for the patch release (v2.23.1)

---

src/views/Returns.vue

Closes #349
Added inputField for facilityId so as to fetch returns for current facility only.

Improved: payload for fetching returns for the selected facility only (#349)

---

package-lock.json
package.json

Updated: app version for the minor release (v2.24.0)

---

package-lock.json
package.json

Improved: app version in package and lock file for minor release(v2.25.0)

---

src/locales/en.json
src/store/modules/order/actions.ts
src/store/modules/shipment/actions.ts
src/utils/index.ts
src/views/AddProductModal.vue
src/views/AddProductToPOModal.vue
src/views/PurchaseOrderDetail.vue
src/views/ShipmentDetails.vue

Related Issue #324
- Added save button in toast to allow user to add product if not found in shipment or POs.
- Added check to not scan if no value provided in sku searching.
Before
After

Implemented: functionality to allow user to add product on scanning (#324)

---

package-lock.json
package.json

Closes #
Updated: app version for minor release (v2.26.0).

Updated: app version for minor release (v2.26.0).

---

package-lock.json
package.json

#
Updated: app version for minor release v2.27.0

Updated: app version for minor release v2.27.0

---

package-lock.json
package.json

https://github.com/hotwax/dxp-components/issues/324
- It added the option of `upc` for product identification.

Improved: Updated the DXP component to v1.15.3 (#324)

---

src/store/modules/shipment/actions.ts
src/views/Shipments.vue

#347 
#
Improved: Fetched shipment attribute while fetching shipment detail (#347).

Improved: Fetched shipment attribute while fetching shipment detail (#347).

---

package-lock.json
package.json

Updated: app version for patch release v2.27.1

---

package-lock.json
package.json

Updated: app version for the patch release (v2.27.2)

---

src/store/modules/shipment/actions.ts

#396
Adding the quantityReceived as 0 while new product is adding to the shipment.

Improved: appending quantityReceived field in the newly added product (#396)

---

package-lock.json
package.json
src/store/modules/user/actions.ts

Improved: updated the oms-api package to latest release and passed token explicitly in the client method when fetching ecom stores

---

package-lock.json
package.json
src/adapter/index.ts
src/main.ts

[345](https://github.com/hotwax/dxp-components/issues/345)
#
Improved: Passed method to fetch good identification types in order to display product identifier options dynamically (#345).

Improved: Passed method to fetch good identification types in order to display product identifier options dynamically (#345).

---

package-lock.json
package.json

Updated: app version for the patch release v2.27.4

---

package-lock.json
package.json

Updated: app version for patch release v2.27.5

---

package-lock.json
package.json

Updated: app version for the minor release (v2.28.0)

---

package-lock.json
package.json

Updated: app version for the patch release (v2.28.1)

---

src/views/Settings.vue

https://github.com/hotwax/receiving/pull/384
- Updated the @updateFacility event binding in <DxpFacilitySwitcher> to pass the updateFacility function directly instead of invoking it with a parameter.

Improved: Refactor <DxpFacilitySwitcher> event binding to directly pass updateFacility function(#dxp-288)

---

package-lock.json
package.json

Updated: app version for patch release v2.29.1

---

package-lock.json
package.json

Updated: app version for patch release v2.29.2

---

src/locales/en.json
src/store/modules/user/actions.ts

#439
Support to redirect user to shipment details page for particular shipment if redirected from transfers app.

Implemented: support to open shipment details page if user is redirected from the transfers app with shipmentId (#439)

---

src/services/ShipmentService.ts
src/store/modules/shipment/actions.ts

#441 
#
Improved: Passed orderId and orderItemSeqId while receiving transfer order shipment (#441).

Improved: Passed orderId and orderItemSeqId while receiving transfer order shipment (#441).

---

package-lock.json
package.json

#447
Improved dxp-components release to fix facility switcher searching issue.

Improved: updated the dependency dxp-components to release v1.19.0 (#447)

---

src/components/ClosePurchaseOrderModal.vue
src/locales/en.json

Fixed: Shortened the error message in the "close purchase items modal" alert appearing on the "Purchase orders" tab and updated its locales. (#448)

---

package-lock.json
package.json

https://github.com/hotwax/dxp-components/issues/350
- Updated dxp-component to v1.20.0 to show dynamically fetched good identifications of type `HC_GOOD_ID_TYPE` in the barcode identifier section

Improved: Updated dxp-component to v1.20.0 for barcode identifier section (dxp/350)

---

src/locales/en.json
src/views/TransferOrderDetail.vue

Fixed: updated the confirmation message for recieve TO confirmation modal. #471

---

src/locales/en.json
src/views/TransferOrderDetail.vue

Fixed: Updated message for transfer order receiving. (#471)

---

package-lock.json
package.json

Improved: app version in package and lock file for minor release(v2.31.0)

---

src/views/TransferOrderDetail.vue

#507 
- Added support to display the QOH for products on TO details page
- Fixed the issue of add product button not being displayed on the UI, this is due to wrong method being called resulting in broken UI
- Fixed a warning for ion-text component due to missing component registration
After:

Implemented: support to display the product qoh on the TO deails page(#507)

---

src/views/TransferOrderDetail.vue

Fixed: code to observe the newly added products so to fetch the QOH correctly(#510)

---

src/views/TransferOrders.vue

#521 
#
Fixed: Excluded rejected transfer orders (#521).

Fixed: Excluded rejected transfer orders (#521).

---

package-lock.json
package.json

Updated: app version for minor release v3.2.0

---

src/components/Menu.vue

#525 
#
Improved: Changed transfer order menu icon to business outline (#525).

Improved: Changed transfer order menu icon to business outline (#525).

---

package-lock.json
package.json

#530 
#
Upgraded dxp-component version to v1.22.2 (#530)

Upgraded dxp-component version to v1.22.2 (#530)

---

package-lock.json
package.json

Updated: app version for minor release v3.3.0

---

src/views/TransferOrderDetail.vue

fix: resolve inconsistent item quantity display between Fulfillment and Receiving apps (#540)

---

package-lock.json
package.json

Updated: app version for patch release v3.3.1.

---

src/store/modules/order/actions.ts
src/store/modules/party/actions.ts

…rdetail
#551 
Fixed : Handle the case when first and lastname are  missing showing receieverLoginId rather than showing null on UI

fixed:fixes and handle the case when name are not present in reecieverDetail(#551)
