changelogs/unreleased/-20d7jmt.yml
src/store/modules/shipment/actions.ts
src/views/Settings.vue

Shipment list is not getting cleared after logout or changing store.
Closes #
Done the changes as this will not show the previous shipments when no shipments found for the current store

Implemented: code to clear the shipments after changing store and logout(#20d7jmt)

---

changelogs/unreleased/-220kt0h.yml
src/views/Receiving.vue
src/views/Settings.vue

Unable to switch screen when on mobile devices
Closes #
Added the ion-menu-button component on the screens
After:

Fixed: code to add the ion-menu-button on mobile devices(#220kt0h)

---

src/views/AddProductModal.vue
src/views/AddProductToPOModal.vue
src/views/PurchaseOrders.vue

Closes #
:- Worked on improving the code to assign input field to instance variable for searchbar.
Because when performing any action on search with enter key, the value of instance variable is set after the action is performed due to which wrong data is passed to API.

Improved: code to assign input field to instance variable for searchbar (#2cj8nc4).

---

src/views/PurchaseOrderDetail.vue

Closes #
When updating product order quantity, quantity does not update, only on reloading the page, quantity updates.
https://user-images.githubusercontent.com/62360781/191028099-e8279d0c-d50b-4d01-a21f-143bca796fdd.mov

Fixed: PO details not updated after changing qty(#2te5d34)

---

src/components/ReturnListItem.vue
src/i18n.ts
src/locales/en.json
src/store/modules/return/actions.ts
src/store/modules/shipment/actions.ts
src/views/ReturnDetails.vue
src/views/Returns.vue
src/views/Settings.vue

Closes #
Light Mode
https://user-images.githubusercontent.com/62360781/192193563-59e00800-73bb-42fb-955f-0c34f3ef804a.mov
Dark Mode
https://user-images.githubusercontent.com/62360781/191977548-ca4a462e-bfa9-4efa-a4db-60453deb5f1e.mov

Improved: Returns page & returns-detail page(#2v7gpv1)

---

src/store/modules/return/actions.ts

When creating payload for receiveShipmentItem, we are accessing shipmentItemSeqId on item that is not available.
Closes #
Updated the property name to itemSeqId

Fixed: issue of shipmentItemSeqId not being passed when receiving shipment item

---

src/store/modules/shipment/actions.ts

Closes #
- Shipment count on wasn't updated when you add an item to the shipment.
- Refresh was needed for the change to take place initially. 
- The issue was there due to wrong variable names in the respective action updateProductCount.
- Changing the names to the ones matching the API response and with the one used in ShipmentListItem fixed the issue.

Fixed: Shipment count not being updated on the Shipments page on  adding an item from Shipment details page. (#2u59n2d)

---

src/utils/index.ts
src/views/PurchaseOrderDetail.vue

Closes #153
- Adds copy icon on order id chip of PurchaseOrderDetail
- Uses @capacitor plugin to copy to clipboard
Did not found how I could have done that, if instructions are provided I'd be welcome

Implemented: feature to copy internal id to clipboard on the detail page for POs

---

src/store/modules/order/actions.ts

Closes #137 
Fixes toast message not being displayed when no orders exist and the user clicks Load more orders button.

Fixed: Displaying toast message when no orders found on clicking Load more Purchase orders (#2vjux71)

---

src/views/PurchaseOrderDetail.vue
src/views/ReceivingHistoryModal.vue

Closes #151 
Upon clicking the 'received' chip on the PO details page, the receiving history of that shipment item will be shown in the modal.
https://user-images.githubusercontent.com/59442907/210532465-9f04b53b-5d8e-4da9-943e-1464286570e8.webm

Implemented: showing receiving history upon clicking on shipment item 'received' chip (#85zrhcn67)

---

src/views/ReturnDetails.vue

Closes #
When we want to receive all return shipments, we always will get one item, so its unnecessary to use filter and loop over whole current items array. So we will use find here so as soon as we meet the condition, it returns without looping over array.

Fixed: Logic to recieveAll returns on return-details page(#2t2wcjr)

---

src/components/ShipmentListItem.vue
src/store/modules/shipment/actions.ts
src/views/Shipments.vue

Closes #249 
Improved: Displayed External Order ID (Transfer Order # in case of transfer shipment from Netsuite) on Shipments page. Also enabled search on the same. (249)

Improved: Displayed External Order ID on Shipments page. Also enabled search on the same. (249)

---

src/components/Menu.vue

Related Issue: https://github.com/hotwax/dxp-components/issues/122
Fixed issue of menu not being enabled for the correct page when using the back button in Receiving app.
- Removed a watcher from the menu component that checks for route changes
- Defined a computed property to find the correct index in the menu list
- Added an entry in the menu component pages to list all the child routes those are not listed in the menu for a specific parent route, using which we have enabled the correct menu in the UI.
- Added a logic for the dynamic child routes in the app.

Implemented: Page Selection Persistence for Receiving App with Side Navigation(#122)

---

src/components/ClosePurchaseOrderModal.vue

Closes #278
Improved code to auto select Items which are receivied in their entirety in the receive and close button modal.

Improved: code to auto select items which are received in their entirety in receive and close modal (#278)

---

src/store/modules/order/actions.ts
src/store/modules/return/actions.ts
src/store/modules/shipment/actions.ts

Closes #308 
Resolved scanning failure caused by empty quantity fields by implementing automatic quantity update when scanning barcodes added toast message display for unavailable products to enhance user feedback.

Fixed: scanning failure issue caused by empty quantity values when scanning barcode  #308

---

src/views/PurchaseOrderDetail.vue

Removed: ion-item and replaced it with ion-buttons as when declaring ion-button inside toolbar we should use ion-buttons Added attributes on the ion-button to match the styling with the figma design
Closes #294
Before:
After:

Fixed: the issue of line after button by improving the html structure(#294)

---

src/store/modules/order/actions.ts

Closes #302 
Removed the toast message when the api fails to fetch the history of purchase orders because if there is no orders in PO history then empty-state is defined so there is no need of  toast message. 

Improved: code by removing toast message when the api for fetching po history fails(#302)

---

src/App.vue
src/locales/en.json
src/store/modules/shipment/actions.ts
src/views/AddProductModal.vue
src/views/AddProductToPOModal.vue
src/views/ShipmentDetails.vue

Fixed: issue in receiving shipment when adding a new item due to missing locationSeqId for that item(#319)

---

src/locales/en.json
src/views/ShipmentDetails.vue

Closes #330
Improved the item card in shipment details page to show static text "shipped" along with shipped item count.

Improved: added the shipped text to be shown with quantity ordered count in item card (#330)

---

src/locales/en.json
src/views/TimezoneModal.vue

Closes #
Spinner is added to show that the timezones are being fetched from the API. It is indicating to the user that the data is loading.

Implemented: Spinner in timezone modal so users can see that data is being fetched

---

src/store/modules/user/actions.ts

Closes #337
Moved loader displaying logic only when user is authorized
Before:
https://github.com/hotwax/receiving/assets/41404838/0c73f90d-5d5a-49e3-9d1b-cb52e1fb851a
After:
https://github.com/hotwax/receiving/assets/41404838/63eb77c9-fc9f-4000-af70-b01306244cc2

Fixed: logout loader on login by only displaying the loader when user is authorized(#337)

---

src/views/PurchaseOrderDetail.vue
src/views/ReturnDetails.vue
src/views/ShipmentDetails.vue

Closes #345
Improved code to show green progress bar when receiving completes to items ordererd.

Improved: made progress bar green when receiving complete (#345)

---

src/components/ClosePurchaseOrderModal.vue
src/store/modules/order/actions.ts

Related Issue #342
- Updating PO item status to "ITEM_COMPLETED" once it is successfully closed.
- Removing PO from the state once all the items of a PO is closed.

Improved: logic to update state on closing PO items status(#342)

---

src/locales/en.json
src/store/modules/order/actions.ts
src/store/modules/return/actions.ts
src/store/modules/shipment/actions.ts

Changed toast message to be more detailed. 
Closes #

Toast message change

---

src/views/ReturnDetails.vue

Related Issue #343
Fixed logic to update return product items status after receiving it completely to avoid multiple receivement of a return.

Fixed: returns status not updating after succesfully receiving it (#343)

---

src/store/modules/order/actions.ts
src/store/modules/return/actions.ts
src/store/modules/shipment/actions.ts
src/views/PurchaseOrderDetail.vue
src/views/ReturnDetails.vue
src/views/ShipmentDetails.vue

Related Issue #367
Fixed scanning issue when using barcode reader as a keyboard input event.
- Clearing the scanned SKU from the ion-input after scanning it succesfully.
- Improved code to highlight the scanned item and scrollIntoView.
[Screencast from 05-04-24 10:55:29 AM IST.webm](https://github.com/hotwax/receiving/assets/69574321/f34ec607-82d6-45eb-9c7a-596b65e4abe8)
[Screencast from 09-04-24 12:34:49 PM IST.webm](https://github.com/hotwax/receiving/assets/69574321/f9b7125d-beeb-48fe-b37d-69d07b458c41)

Improved: logic to clear the scanned SKU from the ion-input once successfully scanned and highlight scanned items (#367)

---

src/locales/en.json
src/views/PurchaseOrderDetail.vue

Related Issue #367
Improved the toast message to be shown in case of scanning completed item.
Before
After

Improved: toast message to be shown in case of scanning completed item (#367)

---

src/views/AddProductModal.vue
src/views/AddProductToPOModal.vue

https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.

Fixed: infinite scroll issue when used with searchbar(dxp-289) 

---

src/store/modules/shipment/actions.ts
src/views/Shipments.vue

Closes #347
Improved: Added support to search by external order name shipment attribute on shipments screen.

Improved: Added support to search by external order name shipment attribute on shipments screen.

---

src/views/PurchaseOrders.vue

#382
Updated the hook used for fetching purchase order.

Fixed: Purchase Orders of Previous Facility Displayed After Changing Facility (#382)

---

src/store/modules/shipment/actions.ts
src/views/ShipmentDetails.vue

#390
Made the receive shipment item synchronous.

Improved: making receipt shipment items in sync instead of using async (#390)

---

src/views/ReturnDetails.vue

#399 
When ShopifyOrderName and HC OrderID are missing, the header now displays alternative identifiers External ID. If no such identifiers is available, a placeholder message "Return" is shown ensuring the header is not blank.

fixed: Blank header appears on return detail page if ShopifyOrderName and HC OrderID are not present (#399)

---

src/locales/en.json
src/views/PurchaseOrderDetail.vue
src/views/ShipmentDetails.vue

#380
Using label instead of badge to show received and ordered items count.

Improved: ui to show received and ordered counts of completed items (#380)

---

src/locales/en.json
src/services/ProductService.ts
src/services/ShipmentService.ts
src/views/ReturnDetails.vue
src/views/ShipmentDetails.vue

#416 
- Added support to display the quantity on hand `(QOH)` of a product at the currently selected facility.
- Added a cube icon that, when clicked, shows an ion-chip displaying the QOH for that line item.
- Fetched the information from the `getInventoryAvailableByFacility` service.

Implemented: Show quantity on hand inventory during receiving(#416)

---

src/views/ReturnDetails.vue
src/views/ShipmentDetails.vue

#416 
- Added a check to handle the case when the API fails or something happens that causes it to return an empty string. In that case, the UI updates to show the cube icon instead of the quantity on hand.

Improved: added check to handle empty string on qoh fetching api fail(#416)

---

src/locales/en.json
src/views/PurchaseOrderDetail.vue
src/views/ReturnDetails.vue
src/views/ShipmentDetails.vue

#421
Fixed issue in the searching in case of searching using barcode identification other than the sku. Hence made the id in the product item dynamic to the barcode identification value of the product.

Improved: made product item id and class dynamic to the barcode identification value of the product (#421)

---

src/views/ReturnDetails.vue
src/views/ShipmentDetails.vue

#429 
- After a shipment or return, the user can see the updated inventory in the "Completed" tab.  
- Clearing the `productQoh` variable in `ionViewDidLeave`, which holds the product quantity on hand (QoH), ensures that when the user switches tabs, the updated QoH is fetched.

Improved: Inventory will update after shipment & return(#429)

---

src/store/modules/user/actions.ts
src/store/modules/util/actions.ts

#436 
- Added a check during login: If the selected facility does not have an associated product store, `Force Scanning` and `Bar Code Identifier` will be set to their default values.  
- Similarly, after updating the facility, if no product store is found, the default settings will be applied.

Fixed: Added checks to prevent updating Force Scanning and Bar Identifiers settings when no product store(#436)

---

src/views/PurchaseOrders.vue
src/views/Returns.vue
src/views/Shipments.vue

#428 
- Fixed a navigation issue where selectedSegment was not set to "open" when navigating back from a page other than the details page.

Fixed: Incorrect Tab Opens After Navigating Between Sections from Order Details Page (#428)

---

src/store/modules/product/actions.ts

#395 
- Previously, the findProduct action did not clear the product list state when the API returned an empty response, resulting in the previous list persisting on an invalid search instead of displaying an empty state.
- Added logic to clear the product state in this case, which fixed the issue.

Fixed: Handled the case of emptying the product list on invalid search in AddProductToPOModal (#395)

---

src/store/modules/transferorder/actions.ts

#475 
replaced the wrong key totalIssuedQuantity with quantityAccepted in the updateProductCount action and added null check so the scanned item quantity increases.
[Screencast from 22-05-25 01:42:12 AM IST.webm](https://github.com/user-attachments/assets/42ee1f13-e963-467c-a8e4-4c25d6ac7693)

Fixed: replaced the wrong key totalIssuedQuantity with quantityAccepted in the updateProductCount action, Scanned item quantity now increases. (#475)

---

src/store/modules/transferorder/actions.ts
src/views/TransferOrders.vue

#476 
Enhanced transfer order pagination:
On initial load, the order list is replaced with new results or cleared if none are found.
On "Load More", new results are concatenated to the existing list; if no more results, a toast ("Transfer orders not found") is shown and the list is not updated.
[Screencast from 22-05-25 12:48:09 PM IST.webm](https://github.com/user-attachments/assets/2e504015-12b0-41df-85d5-3dabcb5aea3d)

Fixed: improved error handling and pagination logic in transfer order actions and view. (#476)

---

src/components/CloseTransferOrderModal.vue

#492 
Added checkAlreadyFulfilledItems method to show partially received items or items with quantity as checked.
[Screencast from 27-05-25 04:14:14 PM IST.webm](https://github.com/user-attachments/assets/39ee40f5-fde1-4734-ab04-d88be6613e0d)

Fixed: add checkAlreadyFulfilledItems method to show partially received items or items with quantity as checked. (#942)

---

src/store/modules/transferorder/actions.ts

#494 
Update condition to check for orders length instead of orderCount  in fetchTransferOrders action.
It checks for array item, if there are item the list is incremented, else the error toast is shown.
[Screencast from 27-05-25 06:58:35 PM IST.webm](https://github.com/user-attachments/assets/97b87666-b78e-4b77-8fb4-3b1068feb13d)

Fixed: update condition to check for orders length instead of orderCount  in fetchTransferOrders action. (#494)

---

src/components/CloseTransferOrderModal.vue

#1222
#
Improved: Added a check to disable items that are not in 'Pending Receipt' status on the Receive and Close modal (#1222).

Improved: Added a check to disable items that are not in 'Pending Receipt' status on the Receive and Close modal (#1222).

---

src/views/ReceivingHistoryModal.vue
src/views/TransferOrderDetail.vue

#519 
#
Fixed: Item receipts history modal showing wrong data in case multiple line items with same product exists in TO .

Fixed: Item receipts history modal showing wrong data in case multiple line items with same product exists in TO (#519).

---

src/services/TransferOrderService.ts
src/store/modules/transferorder/actions.ts
src/views/TransferOrderDetail.vue

#534 
Display Tracking Number on Transfer Order Details Page
Before:
After:

Show Tracking Number on Transfer Order Details Page #534
